# Generated by Django 2.2 on 2021-08-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20210809_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_user',
            new_name='user',
        ),
    ]
