# Generated by Django 2.2 on 2021-08-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_auto_20210809_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_comments', to='wall_app.Message')),
                ('poster_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='wall_app.User')),
            ],
        ),
    ]
